# Python tutorial

## 1. Introduction

Python is a high-level object-oriented programming language that was created by Guido van Rossum in 1989. It is currently the most popular programming language. Python is known for its simple script making it easily readable due to its notable use of significant whitespace. 

### Why Python?

- Very simple syntax compared to Java, C, and C++ languages.

- Extensive library and handy tools for developers/programmer.

- Compared with the code of other languages, python code is easy to write and debug. Therefore, its source code is relatively easy to maintain.

- Python helps you to make complex programming simpler. As it internally deals with memory addresses, garbage collection.

- Python is a portable language so that it can run on a wide variety of Operating systems and platforms.


## 2. Python variables and functions

### Declaring a variable

In order to declare a variable in python we just name it and give it a value (No need for specifying the type)

In [ ]:
a = 5
print(a)

Python automatically knows the variable's type.

In [ ]:
type(a)

In [ ]:
print(a+1)
print(a-1)
print(a*2)
print(a**2)

In [ ]:
a+=1
print(a)

In [ ]:
a*=2
print(a)

 Python implements all of the usual operators for Boolean logic, but uses English words rather than symbols (&&, ||, etc.)

In [ ]:
t = True
f = False
print(type(t)) # Prints "<class 'bool'>"
print(t and f) # Logical AND; prints "False"
print(t or f)  # Logical OR; prints "True"
print(not t)   # Logical NOT; prints "False"
print(t != f)  # Logical XOR; prints "True"

### Re-declaring a variable

We can re-declare a variable even after declaring it once.

In [ ]:
a = 10
print(a)
a = 'Hello'
print(a)

### Concatenating Variables

Unlike Java, we cannot concatenate two data types like string and number together.

In [ ]:
a = 'Hello'
b = 4
print(a+b)

In [ ]:
print(a+str(b))

### Local \& Global Variables

In [ ]:
# Declare a variable and initialize it
f = 10
# Global vs. local variables in functions
def someFunction():
# local f
    f = 'Hello'
    return f

In [ ]:
someFunction()

In [ ]:
print(f)

### Deleting a variable

In [ ]:
f = 11
print(f)
del f
print(f)

## 3. Conditional loops

### IF, ELSE, ELIF

In [ ]:
def isequal(x,y):
    if(x < y):
        st= "x is less than y"

    elif (x == y):
        st= "x is same as y"

    else:
        st="x is greater than y"
    print(st)

In [ ]:
isequal(5,8)

### Switch case

In [ ]:
# Function to convert number into string 
# Switcher is dictionary data type here 
def numbers_to_strings(argument): 
    switcher = { 
        0: "zero", 
        1: "one", 
        2: "two", 
    } 
  
    # get() method of dictionary data type returns  
    # value of passed argument if it is present  
    # in dictionary otherwise second argument will 
    # be assigned as default value of passed argument 
    return switcher.get(argument, "nothing") 

In [ ]:
numbers_to_strings(0)

In [ ]:
numbers_to_strings("hi")

## 4. For \& while loops 

In [ ]:
for i in range(6):
    print(i)

In [ ]:
i=1
while(i<6):
    print(i)
    i= i+1

In [ ]:
Months = ["Jan","Feb","Mar","April","May","June"]
for m in Months:
    print(m)

Breakpoint is a unique function in For Loop that allows you to break or terminate the execution of the for loop

In [ ]:
for x in range (10,20):
    if (x == 15): 
        print(x)
        break
    

Continue function, as the name indicates, will terminate the current iteration of the for loop BUT will continue execution of the remaining iterations.

In [ ]:
for x in range (10,20):
    if (x % 2 == 0) : continue
    print(x)

## 5. Lists

A list is the Python equivalent of an array, but is resizeable and can contain elements of different types:

In [ ]:
xs = [3, 1, 7]    # Create a list
print(xs, xs[2])  # Prints "[3, 1, 2] 2"

In [ ]:
print(xs[0])

In [ ]:
print(xs[-3])     # Negative indices count from the end of the list; prints "2"

In [ ]:
xs[2] = 'foo'     # Lists can contain elements of different types
print(xs)         # Prints "[3, 1, 'foo']"

In [ ]:
xs.append('bar')  # Add a new element to the end of the list
print(xs)         # Prints "[3, 1, 'foo', 'bar']"

In [ ]:
x = xs.pop()      # Remove and return the last element of the list
print(x, xs)      # Prints "bar [3, 1, 'foo']"

#### Slicing: 
In addition to accessing list elements one at a time, Python provides concise syntax to access sublists; this is known as slicing:



In [ ]:
nums = list(range(5))     # range is a built-in function that creates a list of integers
print(nums)               # Prints "[0, 1, 2, 3, 4]"

In [ ]:
print(nums[2:4])          # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"

In [ ]:
print(nums[2:])           # Get a slice from index 2 to the end; prints "[2, 3, 4]"

In [ ]:
print(nums[:2])           # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"

In [ ]:
print(nums[:])            # Get a slice of the whole list; prints "[0, 1, 2, 3, 4]"

In [ ]:
print(nums[:-1])          # Slice indices can be negative; prints "[0, 1, 2, 3]"

In [ ]:
nums[2:3] = [8, 9]        # Assign a new sublist to a slice
print(nums) # Prints "[0, 1, 8, 9, 4]"



## 6. Numpy
Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

In [ ]:
import numpy as np

### Arrays

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [ ]:
a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"

In [ ]:
print(a.shape)            # Prints "(3,)"

In [ ]:
print(a)   # Prints "1 2 3"

In [ ]:
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

In [ ]:
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"

In [ ]:
b

In [ ]:
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

Numpy also provides many functions to create arrays:

In [ ]:
a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

In [ ]:
b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"


In [ ]:
c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"


In [ ]:
d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

In [ ]:
e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

#### Slicing: 
Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [ ]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

In [ ]:
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

In [ ]:
# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

In [ ]:
print(a)

## 7. Pandas

Pandas is a very commun library for data science used to manage two-dimensional data tables in Python.

In [ ]:
import pandas as pd

Importing a csv file

In [ ]:
data = pd.read_csv('spam.csv',delimiter=',',encoding='latin-1')

data visualization

In [ ]:
data.head()

dropping unnecessary columns from the dataset

In [ ]:
data.drop(['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'],axis=1,inplace=True)

In [ ]:
data.head()

renaming columns

In [ ]:
data = data.rename(columns={'v1': 'label','v2': 'email'})
data.head(10)

Pie chart

In [ ]:
data['label'].value_counts().plot.pie(title="Spam/Ham pie chart",  autopct='%1.1f%%')

change values of a column

In [ ]:
data.label[data.label == 'ham'] = 0
data.label[data.label == 'spam'] = 1

In [ ]:
data.head()

In [ ]:
print(data.email[2])